# Initial migration - placeholder
# This should be generated by Django makemigrations

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # This is a placeholder migration
        # The actual initial migration should be generated by Django
    ]